[package]
name = "shellby"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
clap_complete = "4.5.35"
clap_mangen = "0.2.24"
jsonc-parser = "0.26.2"

[dev-dependencies]
assert_cmd = "2.0.16"
rustympkglib = "0.1.1"
